### ISSUE TITLE
Significant amount of spelling error needs to be fixed to make the lamba install

### ISSUE THREAD

**Issue by jimshalo10** [alexa/skill-sample-nodejs-the-foodie#2]
While many people will think that spelling errors are simple they are causing execution errors.
Having successfully installed using ASK CLI then when running there is an error and the skill loops
in TEST developer console "Sorry, I can't understand the command. Please say again."

There is not any command given

**Comment by SleepyDeveloper** [comment]
Thanks for your help fixing the errors! I've merged the changes.
