### ISSUE TITLE
Lambda/custom/index.js does not support the intent "ExplainPortionSizeIntent"

### ISSUE THREAD

**Issue by jimshalo10** [alexa/skill-sample-nodejs-the-foodie#3]
<jusjef@amazon.com> @justin 

Lambda/custom/index.js does not support the intent "ExplainPortionSizeIntent"
This can be called by the utterance "tell the foodie how many calories is a large portion"

The output from [Skillinator](https://skillinator.io/) the Interaction Model JSON to Lambda generator works well with the Interaction Model JSON used in the Alexa Developer Console Custom Skill

**Comment by SleepyDeveloper** [comment]
I'm doing a large set of updates to the foodie today. I'll add this to my list of things to update.

**Comment by coe16b015** [comment]
When I invoke the skill, it is responding with there is a problem with the requested skill's response. When I took the json input and tested with the aws code, it suggests that it does have the moment-timezone module. what to do next and how to resolve this?

**Comment by jimshalo10** [comment]
This works in the UK for me. Unfortunately, I do not work with this  anymore as I retired from work on this
